[package]
name = "nlp-wave-1-candidate-consumer"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
"moenarch-text-core" = "=0.1.1"
"moenarch-text-model-runtime" = "=0.1.1"
"moenarch-text-core-cli" = "=0.1.1"
"moenarch-text-core-server" = "=0.1.1"
"moenarch-text-core-wasm" = "=0.1.1"
"moenarch-text-generation" = "=0.1.1"
"moenarch-text-lexical" = "=0.1.1"
"moenarch-text-model-runtime-cli" = "=0.1.1"
"moenarch-text-model-runtime-server" = "=0.1.1"
"moenarch-text-model-runtime-wasm" = "=0.1.1"
"moenarch-text-transcripts" = "=0.1.3"
"moenarch-text-classification" = "=0.1.1"
"moenarch-text-embeddings" = "=0.1.1"
"moenarch-text-generation-cli" = "=0.1.1"
"moenarch-text-generation-server" = "=0.1.1"
"moenarch-text-generation-wasm" = "=0.1.1"
"moenarch-text-lexical-cli" = "=0.1.1"
"moenarch-text-lexical-server" = "=0.1.1"
"moenarch-text-lexical-wasm" = "=0.1.1"
"moenarch-text-linguistics" = "=0.1.1"
"moenarch-text-transcripts-cli" = "=0.1.1"
"moenarch-text-transcripts-server" = "=0.1.1"
"moenarch-text-transcripts-wasm" = "=0.1.1"
"moenarch-text-classification-cli" = "=0.1.1"
"moenarch-text-classification-server" = "=0.1.1"
"moenarch-text-classification-wasm" = "=0.1.1"
"moenarch-text-embeddings-cli" = "=0.1.1"
"moenarch-text-embeddings-server" = "=0.1.1"
"moenarch-text-embeddings-wasm" = "=0.1.1"
"moenarch-text-generation-linguistics" = "=0.1.1"
"moenarch-text-index" = "=0.1.1"
"moenarch-text-linguistics-cli" = "=0.1.1"
"moenarch-text-linguistics-server" = "=0.1.1"
"moenarch-text-linguistics-wasm" = "=0.1.1"
"moenarch-text-generation-linguistics-cli" = "=0.1.1"
"moenarch-text-generation-linguistics-server" = "=0.1.1"
"moenarch-text-generation-linguistics-wasm" = "=0.1.1"
"moenarch-text-index-cli" = "=0.1.1"
"moenarch-text-index-server" = "=0.1.1"
"moenarch-text-index-wasm" = "=0.1.1"
"moenarch-text-retrieval" = "=0.1.1"
"moenarch-text-analysis" = "=0.1.1"
"moenarch-text-question-answering" = "=0.1.1"
"moenarch-text-retrieval-cli" = "=0.1.1"
"moenarch-text-retrieval-server" = "=0.1.1"
"moenarch-text-retrieval-wasm" = "=0.1.1"
"moenarch-text-analysis-cli" = "=0.1.1"
"moenarch-text-analysis-server" = "=0.1.1"
"moenarch-text-analysis-wasm" = "=0.1.1"
"moenarch-text-question-answering-cli" = "=0.1.1"
"moenarch-text-question-answering-server" = "=0.1.1"
"moenarch-text-question-answering-wasm" = "=0.1.1"
